"""add game modes: game_type, game_config, game_state, single_band

Revision ID: 1f4e6601cae7
Revises: a838f4f2385a
Create Date: 2026-08-26 15:35:12.479009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4e6601cae7'
down_revision: Union[str, Sequence[str], None] = 'a838f4f2385a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dart_throws', sa.Column('single_band', sa.String(length=5), nullable=True))
    op.create_check_constraint(op.f('ck_dart_throws_single_band_valid'), 'dart_throws', "single_band IS NULL OR single_band IN ('inner', 'outer')")
    op.add_column('leg_player_states', sa.Column('game_state', sa.JSON(), nullable=True))
    # NOTE: the column stores enum NAMES (like status does), so the
    # backfill default must be 'X01', not the lowercase value.
    op.add_column('matches', sa.Column('game_type', sa.Enum('X01', 'CRICKET', 'HALVE_IT', name='gametype', native_enum=False, length=20), server_default='X01', nullable=False))
    op.add_column('matches', sa.Column('game_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'game_config')
    op.drop_column('matches', 'game_type')
    op.drop_column('leg_player_states', 'game_state')
    op.drop_constraint(op.f('ck_dart_throws_single_band_valid'), 'dart_throws', type_='check')
    op.drop_column('dart_throws', 'single_band')
    # ### end Alembic commands ###
