"""add players.created_by_user_id: who scores for a guest

Guests used to be visible to every account as opponents, and any
account could read any player's statistics. The column records the
account that created each row; registered profiles get their own user
id, and existing guests are backfilled from the creator of the earliest
match they appeared in (guests are only ever scored by the match
creator). Guests that never played stay NULL and are listed to no one.

Revision ID: 9db1ef727407
Revises: 3c9d2b7e5a10
Create Date: 2026-10-09 11:30:43.776473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db1ef727407'
down_revision: Union[str, Sequence[str], None] = '3c9d2b7e5a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_players_created_by_user_id_users'), 'players', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###

    # Registered profiles belong to their own account.
    op.execute("UPDATE players SET created_by_user_id = user_id WHERE user_id IS NOT NULL")
    # Guests: the creator of the earliest match they appeared in.
    op.execute(
        """
        UPDATE players AS p
        SET created_by_user_id = first_match.created_by_user_id
        FROM (
            SELECT DISTINCT ON (appearances.player_id)
                   appearances.player_id, appearances.created_by_user_id
            FROM (
                SELECT player1_id AS player_id, created_by_user_id, created_at FROM matches
                UNION ALL
                SELECT player2_id AS player_id, created_by_user_id, created_at FROM matches
            ) AS appearances
            ORDER BY appearances.player_id, appearances.created_at
        ) AS first_match
        WHERE p.id = first_match.player_id
          AND p.user_id IS NULL
          AND p.bot_difficulty IS NULL
          AND p.created_by_user_id IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_players_created_by_user_id_users'), 'players', type_='foreignkey')
    op.drop_column('players', 'created_by_user_id')
    # ### end Alembic commands ###
