"""initial schema: users, players, matches, legs, leg_player_states, turns, dart_throws

Revision ID: a838f4f2385a
Revises: 
Create Date: 2026-08-26 10:13:54.174867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a838f4f2385a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_players_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('player1_id', sa.Uuid(), nullable=False),
    sa.Column('player2_id', sa.Uuid(), nullable=False),
    sa.Column('best_of_legs', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='matchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('winner_player_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # NOTE: single % here, not %%. The driver escapes % once at execution
    # time; autogenerate wrote %% which escaped to %%%% and broke PostgreSQL.
    sa.CheckConstraint('best_of_legs > 0 AND best_of_legs % 2 = 1', name=op.f('ck_matches_best_of_legs_odd')),
    sa.CheckConstraint('player1_id != player2_id', name=op.f('ck_matches_players_distinct')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_matches_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], name=op.f('fk_matches_player1_id_players')),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], name=op.f('fk_matches_player2_id_players')),
    sa.ForeignKeyConstraint(['winner_player_id'], ['players.id'], name=op.f('fk_matches_winner_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('legs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('leg_number', sa.SmallInteger(), nullable=False),
    sa.Column('starting_player_id', sa.Uuid(), nullable=False),
    sa.Column('winner_player_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='legstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('leg_number > 0', name=op.f('ck_legs_leg_number_positive')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_legs_match_id_matches')),
    sa.ForeignKeyConstraint(['starting_player_id'], ['players.id'], name=op.f('fk_legs_starting_player_id_players')),
    sa.ForeignKeyConstraint(['winner_player_id'], ['players.id'], name=op.f('fk_legs_winner_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legs')),
    sa.UniqueConstraint('match_id', 'leg_number', name='uq_legs_match_leg_number')
    )
    op.create_table('leg_player_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('leg_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('remaining_score', sa.SmallInteger(), nullable=False),
    sa.Column('darts_thrown', sa.Integer(), nullable=False),
    sa.Column('turns_taken', sa.Integer(), nullable=False),
    sa.Column('has_won', sa.Boolean(), nullable=False),
    sa.CheckConstraint('darts_thrown >= 0', name=op.f('ck_leg_player_states_darts_thrown_non_negative')),
    sa.CheckConstraint('remaining_score >= 0 AND remaining_score != 1', name=op.f('ck_leg_player_states_remaining_score_legal')),
    sa.CheckConstraint('turns_taken >= 0', name=op.f('ck_leg_player_states_turns_taken_non_negative')),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], name=op.f('fk_leg_player_states_leg_id_legs')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_leg_player_states_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leg_player_states')),
    sa.UniqueConstraint('leg_id', 'player_id', name='uq_leg_player_states_leg_player')
    )
    op.create_table('turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('leg_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('turn_start_score', sa.SmallInteger(), nullable=False),
    sa.Column('turn_end_score', sa.SmallInteger(), nullable=False),
    sa.Column('points_scored', sa.SmallInteger(), nullable=False),
    sa.Column('is_bust', sa.Boolean(), nullable=False),
    sa.Column('is_checkout', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_bust AND turn_end_score = turn_start_score AND points_scored = 0) OR (NOT is_bust AND points_scored = turn_start_score - turn_end_score)', name=op.f('ck_turns_bust_preserves_score')),
    sa.CheckConstraint('NOT (is_bust AND is_checkout)', name=op.f('ck_turns_bust_xor_checkout')),
    sa.CheckConstraint('NOT is_checkout OR turn_end_score = 0', name=op.f('ck_turns_checkout_ends_at_zero')),
    sa.CheckConstraint('points_scored >= 0 AND points_scored <= 180', name=op.f('ck_turns_points_in_range')),
    sa.CheckConstraint('turn_number > 0', name=op.f('ck_turns_turn_number_positive')),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], name=op.f('fk_turns_leg_id_legs')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_turns_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turns')),
    sa.UniqueConstraint('leg_id', 'turn_number', name='uq_turns_leg_turn_number')
    )
    op.create_table('dart_throws',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('dart_number', sa.SmallInteger(), nullable=False),
    sa.Column('segment', sa.String(length=4), nullable=False),
    sa.Column('multiplier', sa.SmallInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('is_double', sa.Boolean(), nullable=False),
    sa.Column('is_checkout_attempt', sa.Boolean(), nullable=False),
    sa.Column('is_winning_dart', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_winning_dart OR is_double', name=op.f('ck_dart_throws_winning_dart_is_double')),
    sa.CheckConstraint('dart_number BETWEEN 1 AND 3', name=op.f('ck_dart_throws_dart_number_1_to_3')),
    sa.CheckConstraint('multiplier BETWEEN 0 AND 3', name=op.f('ck_dart_throws_multiplier_0_to_3')),
    sa.CheckConstraint('score >= 0 AND score <= 60', name=op.f('ck_dart_throws_score_in_range')),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], name=op.f('fk_dart_throws_turn_id_turns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dart_throws')),
    sa.UniqueConstraint('turn_id', 'dart_number', name='uq_dart_throws_turn_dart')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dart_throws')
    op.drop_table('turns')
    op.drop_table('leg_player_states')
    op.drop_table('legs')
    op.drop_table('matches')
    op.drop_table('players')
    op.drop_table('users')
    # ### end Alembic commands ###
