"""unique profile per account and bot per difficulty; seed bots

"One profile per account" and "one bot per difficulty" were enforced
only by a select-then-insert in the service, so two concurrent first
requests could both insert. Partial unique indexes now back both
rules. The five shared bots are created here (only the missing ones,
so an existing database keeps its rows and their match history)
instead of being inserted by GET /players/bots, which is a safe method
and must not write.

Revision ID: afe17201913e
Revises: 9db1ef727407
Create Date: 2026-10-09 11:57:49.934605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe17201913e'
down_revision: Union[str, Sequence[str], None] = '9db1ef727407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mirrors app.scoring.bot.BotDifficulty and app.players.service.BOT_DISPLAY_NAMES;
# spelled out here so the migration never depends on application code.
BOTS = [
    ("noob", "Noob Bot"),
    ("easy", "Easy Bot"),
    ("medium", "Medium Bot"),
    ("hard", "Hard Bot"),
    ("pro", "Pro Bot"),
]


def upgrade() -> None:
    """Upgrade schema."""
    for difficulty, name in BOTS:
        op.execute(
            sa.text(
                "INSERT INTO players (id, user_id, display_name, nickname, is_active, bot_difficulty) "
                "SELECT gen_random_uuid(), NULL, :name, NULL, true, :difficulty "
                "WHERE NOT EXISTS (SELECT 1 FROM players WHERE bot_difficulty = :difficulty)"
            ).bindparams(name=name, difficulty=difficulty)
        )
    # Fails loudly if a database already holds duplicates; those rows
    # carry match history and must be merged by hand, not dropped here.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_players_bot_difficulty', 'players', ['bot_difficulty'], unique=True, postgresql_where=sa.text('bot_difficulty IS NOT NULL'))
    op.create_index('uq_players_user_id', 'players', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_players_user_id', table_name='players', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_players_bot_difficulty', table_name='players', postgresql_where=sa.text('bot_difficulty IS NOT NULL'))
    # ### end Alembic commands ###
