"""indexes for match listing and statistics

The only indexes so far came from primary keys and unique constraints.
list_matches filters by creator and by either player and orders by
created_at; every career statistic aggregates turns by player_id.

Revision ID: efc6784364cf
Revises: afe17201913e
Create Date: 2026-10-09 12:01:34.052581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc6784364cf'
down_revision: Union[str, Sequence[str], None] = 'afe17201913e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_matches_created_at'), 'matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_matches_created_by_user_id'), 'matches', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_matches_player1_id'), 'matches', ['player1_id'], unique=False)
    op.create_index(op.f('ix_matches_player2_id'), 'matches', ['player2_id'], unique=False)
    op.create_index(op.f('ix_turns_player_id'), 'turns', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_player_id'), table_name='turns')
    op.drop_index(op.f('ix_matches_player2_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_player1_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_created_by_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_created_at'), table_name='matches')
    # ### end Alembic commands ###
